---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: awsgp2
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: awsio1
provisioner: kubernetes.io/aws-ebs
parameters:
  type: io1 
  #zone: us-east-1a
  zones: us-east-2a
  iopsPerGB: "5"
 
 
 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auto-assign-pv-1
spec:
  storageClassName: high
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auto-assign-pv-2
spec:
  storageClassName: medium
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auto-assign-pv-1
spec:
  storageClassName: awsgp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auto-assign-pv-2
spec:
  storageClassName: awsio1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auto-assign-pv-3
spec:
  storageClassName: awsgp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
      name: mongodb
  template:
    metadata:
      labels:
        app: mongodb
        name: mongodb
    spec:
      containers:
      - image: mongo
        name: mongodb
        imagePullPolicy: Always
        volumeMounts:
        - name: mongodb-data-1
          mountPath: /data/db
        - name: mongodb-data-2
          mountPath: /data/db2
        - name: mongodb-data-3
          mountPath: /data/db3
      volumes:
      - name: mongodb-data-1
        persistentVolumeClaim: 
          claimName: auto-assign-pv-1
      - name: mongodb-data-2
        persistentVolumeClaim: 
          claimName: auto-assign-pv-2
      - name: mongodb-data-3
        persistentVolumeClaim: 
          claimName: auto-assign-pv-3
